---

- hosts: localhost
  become: true
  pre_tasks:

  - name: Apache installation
    tags: always
    package:
        name:
          - "{{ apache_package }}"
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: Start apache
    tags: apache, apache2, httpd
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: change e-mail adress for admin
    tags: apache, apache2, httpd
    lineinfile:
       path: /etc/apache2/apache2.conf
       regexp: '^ServerAdmin'
       line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "Ubuntu"
    register: apache2

  - name: restart apache2
    tags: apache, centos, apache2
    service:
       name: apace2
       state: restarted
    when: apache2.changed

#---------------------

- hosts: localhost
  become: true
  tasks:

  - name: PHP installation
    tags: apache, apache2, ubuntu
    package:
        name:
           - "{{ php_package }}"

  - name: Copy default HTML
    tags: apache,apache2, ubuntu
    copy:
      src: defaut_site.html
      dest: /var/www/html/index_ansible.html
      owner: root
      group: root
      mode: 0644

- hosts: localhost # <-- Target Host
  become: yes # <-- A diectiive indicate that the task should be executed with elevated privileges
  tasks: # <-- Declare the tasks that we gonna automate it

  - name: install unzip  # <-- Our first task: install yhe unzip package
    package:
       name: unzip

  - name: install terraform # Our second task: install terraform
    unarchive:
        src: https://releases.hashicorp.com/terraform/1.4.2/terraform_1.4.2_linux_amd64.zip # <-- Download link
        dest: /usr/local/bin # <-- Is where we gonna store terraform in the target host
        remote_src: yes # <-- This is something downloaded from the internet 
        mode: 0755 # <-- The permissions of the file that is extracted from the zip file
        owner: root # <-- The owner of the file
        group: root # <-- the group too

#-------------------------
# Adding Users

- hosts: localhost
  become: yes
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
       user: simone
       key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJQItm7qPeq9PYzl0iKcwMoggbTaLXnpe9DbLt4h7vbJ ansible"


