---

- hosts: localhost
  become: true
  pre_tasks:

  - name: 1
    tags: always 
    package:
        name:
          - "{{ apache_package }}"
    when: ansible_distribution in ["Ubuntu","Debian"]

- hosts: localhost
  become: true
  tasks:

  - name: 2
    tags: apache, apache2, ubuntu
    package:
        name:
           - "{{ apache_package  }}"
           - "{{ php_package }}"


