---

- hosts: localhost
  become: true
  pre_tasks:

  - name: Apache installation
    tags: always
    package:
        name:
          - "{{ apache_package }}"
    when: ansible_distribution in ["Ubuntu","Debian"]


- hosts: localhost
  become: true
  tasks:

  - name: PHP installation
    tags: apache, apache2, ubuntu
    package:
        name:
           - "{{ apache_package  }}"
           - "{{ php_package }}"

  - name: Copy default HTML
    tags: apache,apache2, ubuntu
    copy:
      src: defaut_site.html
      dest: /var/www/html/index_ansible.html
      owner: root
      group: root
      mode: 0644

- hosts: localhost # <-- Target Host
  become: yes # <-- A diectiive indicate that the task should be executed with elevated privileges
  tasks: # <-- Declare the tasks that we gonna automate it

  - name: install unzip  # <-- Our first task: install yhe unzip package
    package:
       name: unzip

  - name: install terraform # Our second task: install terraform
    unarchive:
        src: https://releases.hashicorp.com/terraform/1.4.2/terraform_1.4.2_linux_amd64.zip # <-- Download link
        dest: /usr/local/bin # <-- Is where we gonna store terraform in the target host
        remote_src: yes # <-- This is something downloaded from the internet 
        mode: 0755 # <-- The permissions of the file that is extracted from the zip file
        owner: root # <-- The owner of the file
        group: root # <-- the group too

# Omar BARKALLAH: DevOps & Cloud consultant @ Fogits-odoo silver partner




