---

- hosts: localhost
  become: true
  pre_tasks:

  - name: install apache2 package 
    package:
        name:
          - "{{ apache_package }}"
    when: ansible_distribution in ["Ubuntu","Debian"]

- hosts: localhost
  become: true
  tasks:

  - name: install php package
    package:
        name:
           - "{{ php_package }}"


